# Generated by Django 5.2.14 on 2026-05-31 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("github_url", models.URLField(max_length=512, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("cloning", "Cloning"),
                            ("parsing", "Parsing"),
                            ("indexing", "Indexing"),
                            ("generating_overview", "Generating Overview"),
                            ("ready", "Ready"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("file_count", models.IntegerField(default=0)),
                ("chunk_count", models.IntegerField(default=0)),
                ("summary", models.TextField(blank=True)),
                ("tech_stack", models.JSONField(default=dict)),
                ("languages", models.JSONField(default=list)),
                ("important_components", models.JSONField(default=list)),
                ("learning_path", models.JSONField(default=list)),
                ("architecture_diagram", models.TextField(blank=True)),
                ("folder_structure", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "repositories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CodeChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.CharField(max_length=1024)),
                ("chunk_text", models.TextField()),
                ("chunk_index", models.IntegerField(default=0)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="repositories.repository",
                    ),
                ),
            ],
            options={
                "ordering": ["file_path", "chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="RepositoryFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=1024)),
                ("content", models.TextField()),
                ("language", models.CharField(blank=True, max_length=50)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="repositories.repository",
                    ),
                ),
            ],
            options={
                "unique_together": {("repository", "path")},
            },
        ),
    ]
