# Generated by Django 5.2.14 on 2026-08-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repositories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="celery_task_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
